#! /usr/bin/env python

from __future__ import print_function
import sys
import os

try:
    filename = __file__
except:
    __file__ = sys.executable
else:
    del filename
app_lib = os.path.join(os.path.dirname(os.path.realpath(__file__)))
print("Launching Ryouko from " + app_lib)
sys.path.append(app_lib)

import ryouko_lib.ryouko

if __name__ == "__main__":
    ryouko_lib.ryouko.main()
